server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TERMOUSSI-LAMIAA/MicroBank.git
          default-label: master
          search-paths: backend/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud: DEBUG
